---
version: '3'
services:
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "test:3:1,test-valid:1:1,test-invalid:1:1,test-error:1:1,tests-v1:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: wurstmeister/zookeeper
    # Somehow the container on my aarch64 machine is not able to set or access
    # ulimits without privileged mode, causing the JVM to dump core O_O
    # <>https://hg.openjdk.java.net/icedtea/jdk7/jdk/rev/028f2ab19545#l78.73>
    privileged: true
    ports:
      - "2181:2181"
